### ISSUE TITLE
ansys-template links in dev guide are broken.

### ISSUE THREAD

**Issue by PipKat** [ansys/pyansys-dev-guide#306]
### Description of the modifications

Kelly Fletcher told me that the ansys-template links are broken. I assume that this is because of the account move. I'll assign myself to fix this but might not get to it before I leave on a two-week vacation on 5/24.

### Useful links and references
@RobPasMue @jorgepiloto  I think there are a lot of confusing things happening in this dev guide page: https://dev.docs.pyansys.com/packaging/templates.html#the-ansys-templates-tool

The referenced tool is internal, residing in the Ansys-internal account. Should we even be talking about it in the Ansys dev guide? (Note that the [ansys-templates](https://github.com/ansys-internal/ansys-templates) repo page has no link to its [doc](https://templates.ansys.com/version/dev/).)  

On the dev guide's [Templates](https://dev.docs.pyansys.com/packaging/templates.html#the-ansys-templates-tool) page, the **Repository** and **Issues board** links go to the solution-templates repository or pages in this repository, which I assume are wrong. This repo, which belongs to the Solutions team, is also internal--and definitely not the ansys-templates links that I think should be used.

Links to **specific** sections of the correct guide for the ansys-templates repository, like [ansys-templates user guide](https://templates.ansys.com/user_guide/index.html), are broken. They display "Page not found" errors. Do I simply add the ``dev`` folder in the path? This is the URL when I go to this section in the doc: https://templates.ansys.com/version/dev/getting_started/index.html. I believe that this guide will aways be available only in a dev version. If this is correct, I assume that I use this URL. However, in docs that have multi-versions, how do I link a specific section of a doc?

Given guidance, I can clean up this dev guide page. However, I first want to ensure that what I perceive as errors actually are errors. I'm thinking that perhaps this content should only appear in the doc for the ansys-templates repo? Or, do we specify in the dev guide that this content is only for Ansys employees? I don't think there is a way to use conditional statements to show it only to those who log it through SSO, but maybe?

**Comment by akaszynski** [comment]
This will be back online soon, probably Tuesday.

**Comment by PipKat** [comment]
@RobPasMue @jorgepiloto Just wanting to bring this issue to your attention again. It's likely not a priority, but I've been watching it to see if either of you have added comments.

**Comment by RobPasMue** [comment]
Hi @PipKat! We are aware of the issue. @jorgepiloto is working on getting the package back online, together with its docs. We will close it once its finished =)

**Comment by RobPasMue** [comment]
This should now be solved =)
