### ISSUE TITLE
Adding a list of abbreviations to the Getting Started section of the dev guide

### ISSUE THREAD

**Issue by RobPasMue** [ansys/pyansys-dev-guide#316]
Following #315 and coming from @PipKat's feedback, we should gather a list of commonly used acronyms. Could you take care of this @PipKat? Really appreciated!!

**Comment by PipKat** [comment]
Changed the description fromr ``User guide`` to ``Getting started`` as there is no ``User guide`` section in the PyAnsys Developer's Guide!

**Comment by RobPasMue** [comment]
My bad... I was on autopilot mode when I wrote the description, thanks for being on top of it! 😄
