### ISSUE TITLE
Modify "The AUTHORS.md file" section in packaging/structure.html

### ISSUE THREAD

**Issue by PipKat** [ansys/pyansys-dev-guide#318]
### Description of the modifications

Based on a recent PyAnsys developer's meeting, the AUTHORS.MD file use is for ANSYS, INC. and possibly external contributors who request that they be added. Update this section and add a "The CONTRIBUTORS.MD file" section. to explain how it is a list of names for maintainers and contributors.

### Useful links and references

https://dev.docs.pyansys.com/packaging/structure.html

**Comment by RobPasMue** [comment]
Ah, good call @PipKat! As soon as https://github.com/ansys/pygeometry/pull/561 is merged, I'll get to this

Thanks for opening the issue! =)

**Comment by RobPasMue** [comment]
Working on this!
