### ISSUE TITLE
Automation for link integrity verification

### ISSUE THREAD

**Issue by RobPasMue** [ansys/pyansys-dev-guide#324]
I implemented something on the ``pyansys`` metapackage that could be useful, at least for this package @jorgepiloto. 

See https://github.com/ansys/pyansys/blob/ca64552ea84566a873e29735ee5c4574074b1428/doc/Makefile#L21-L25

By overriding the ``html`` target, I am forcing ``make`` to run the ``linkcheck`` target first. This ``linkcheck`` what it does is verify that all URLs in our documentation are working fine. We should consider implementing it here (and maybe in our actions?). What do you think @klmcadams @jorgepiloto? Automation is the way to go so if we can have our workflows tell us which links are broken, even better!

_Originally posted by @RobPasMue in https://github.com/ansys/pyansys-dev-guide/issues/323#issuecomment-1602059150_

**Comment by RobPasMue** [comment]
Add it also to the ``make.bat`` file if possible :) many people also do dev on Windows... or are forced to do it on Windows like me - and we would benefit from it as well.

**Comment by MaxJPRey** [comment]
@RobPasMue Should we test the link twice to avoid any false negatives?
In the past, I have experienced on one of the projects I worked on some transient issue -very short period of time, maybe couple ms-.

**Comment by RobPasMue** [comment]
IMO - if it fails due to some kind of transient issue, devs would just have to re-run the workflow. That's what we always do. I'd avoid duplicating tasks scheduled for running.

**Comment by RobPasMue** [comment]
Since this will be implemented in our actions already, it doesn't make much sense to implement it here too. We will have to solve the issues that may raise when we update our actions. Therefore, closing.
