### ISSUE TITLE
Variable issue in PDF section for Makefile

### ISSUE THREAD

**Issue by klmcadams** [ansys/pyansys-dev-guide#397]
### Description of the modifications

Currently:
```
pdf:
        @$(SPHINXBUILD) -M latex "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)
        cd $(BUILDIR)/latex && latexmk -r latexmkrc -pdf *.tex -interaction=nonstopmode || true
        (test -f $(BUILDIR)/latex/*.pdf && echo pdf exists) || exit 1
```

New suggestion - change BUILDIR in lines 2 and 3 to BUILDDIR
```
pdf:
        @$(SPHINXBUILD) -M latex "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)
        cd $(BUILDDIR)/latex && latexmk -r latexmkrc -pdf *.tex -interaction=nonstopmode || true
        (test -f $(BUILDDIR)/latex/*.pdf && echo pdf exists) || exit 1
```

### Useful links and references

Build PDF Documentation, Makefile tab:

https://dev.docs.pyansys.com/how-to/documenting.html#build-documentation

**Comment by Revathyvenugopal162** [comment]
Additionally include the ` .PHONY: pdf` in both the Makefile and make.bat files to facilitate proper execution in both environments.
